### Modulo 2 Lectura de Ficheros

-Hacer las importaciones necesarias para abrir un archivo de tipo csv en Pandas.
-Abrir el archivo, creando un dataframe. Aseguraros de que no incluye la columna "Unnamed: 0".
-Guardar el dataframe en formato Excel y después crear un dataframe con el Excel. ¿El dataframe es similar al que teníais antes?
-Crear una carpeta llamada Files y guardar el mismo archivo en esa carpeta en formato csv .
-Copia el archivo personal.json en la carpeta Files.
-Abre el fichero json (con el json.load(f)) y haz las modificaciones necesarias para que tenga formato de tabla (Para esto necesitas normalizar los datos con el pd.json_normalize).
-Guardar el json modificado y abrirlo en Pandas.¿Cómo queda ahora?

In [34]:
import pandas as pd
import json

In [35]:
df=pd.read_csv("videogames.csv",index_col=0)

In [36]:
df.head(4)

,name,url,year,certificate,rating,votes,plot,Action,Adventure,Comedy,Crime,Family,Fantasy,Mystery,Sci-Fi,Thriller
0,Spider-Man,https://www.imdb.com/title/tt5807780/?ref_=adv...,2018.0,T,9.2,"20,759","When a new villain threatens New York City, Pe...",True,True,False,False,False,True,False,False,False
1,Red Dead Redemption II,https://www.imdb.com/title/tt6161168/?ref_=adv...,2018.0,M,9.7,"35,703",Amidst the decline of the Wild West at the tur...,True,True,False,True,False,False,False,False,False
2,Grand Theft Auto V,https://www.imdb.com/title/tt2103188/?ref_=adv...,2013.0,M,9.5,"59,986",Three very different criminals team up for a s...,True,False,False,True,False,False,False,False,False
3,God of War,https://www.imdb.com/title/tt5838588/?ref_=adv...,2018.0,M,9.6,"26,118","After wiping out the gods of Mount Olympus, Kr...",True,True,False,False,False,False,False,False,False

In [37]:
df.to_excel("df_de_csv_a_excel.xlsx",index=0) #elimina el indice creado al importar el csv

In [ ]:
df2=pd.read_excel("df_de_csv_a_excel.xlsx")     #solo a csv le indicamos index_col=0

In [44]:
df2.head(4)

,name,url,year,certificate,rating,votes,plot,Action,Adventure,Comedy,Crime,Family,Fantasy,Mystery,Sci-Fi,Thriller
0,Spider-Man,https://www.imdb.com/title/tt5807780/?ref_=adv...,2018.0,T,9.2,"20,759","When a new villain threatens New York City, Pe...",True,True,False,False,False,True,False,False,False
1,Red Dead Redemption II,https://www.imdb.com/title/tt6161168/?ref_=adv...,2018.0,M,9.7,"35,703",Amidst the decline of the Wild West at the tur...,True,True,False,True,False,False,False,False,False
2,Grand Theft Auto V,https://www.imdb.com/title/tt2103188/?ref_=adv...,2013.0,M,9.5,"59,986",Three very different criminals team up for a s...,True,False,False,True,False,False,False,False,False
3,God of War,https://www.imdb.com/title/tt5838588/?ref_=adv...,2018.0,M,9.6,"26,118","After wiping out the gods of Mount Olympus, Kr...",True,True,False,False,False,False,False,False,False

In [50]:
df2.to_csv("Files/videojuegos_2.csv", index=False)

In [56]:
json_path="Files/personal.json"
with open(json_path, "r") as file:
    data=json.load(file)
    data_i=data['workers']

In [57]:
data_i

[{'nombre': 'Ana',
  'edad': 34,
  'experiencia': 5,
  'nivel': 'Senior',
  'salario': 50000,
  'mascota': 'gatos'},
 {'nombre': 'Eva',
  'edad': 37,
  'experiencia': 2,
  'nivel': 'Mid',
  'salario': 35000},
 {'nombre': 'Marta',
  'edad': 27,
  'experiencia': 1,
  'nivel': 'Junior',
  'salario': 25000},
 {'nombre': 'Paula',
  'edad': 30,
  'experiencia': 3,
  'nivel': 'Mid',
  'salario': 35000}]

In [59]:
df=pd.json_normalize(data_i)
df

  nombre  edad  experiencia   nivel  salario mascota
0    Ana    34            5  Senior    50000   gatos
1    Eva    37            2     Mid    35000     NaN
2  Marta    27            1  Junior    25000     NaN
3  Paula    30            3     Mid    35000     NaN

In [ ]:
df.to_csv('Files/personal.csv', index=False)            #se guarda tb en .json para ver como se desanida la informacion original

data_i = pd.read_csv("Files/personal.csv")

data_i.head()

  nombre  edad  experiencia   nivel  salario mascota
0    Ana    34            5  Senior    50000   gatos
1    Eva    37            2     Mid    35000     NaN
2  Marta    27            1  Junior    25000     NaN
3  Paula    30            3     Mid    35000     NaN

In [63]:
df.to_json('Files/personal.json', index=False)

data_ii = pd.read_csv("Files/personal.csv")

data_ii.head()

  nombre  edad  experiencia   nivel  salario mascota
0    Ana    34            5  Senior    50000   gatos
1    Eva    37            2     Mid    35000     NaN
2  Marta    27            1  Junior    25000     NaN
3  Paula    30            3     Mid    35000     NaN