### Módulo 2 Python +SQL: Nivel Inicial

Haz las importaciones necesarias para establecer la conexión y trabajar con Pandas. Establece la conexión usando mysql.connector utilizando try/except por si la conexión devuelve un error.
Crea un nuevo "schema" llamado "alumnas-promo-X"
Crea una tabla con la información de las alumnas de la promo. Debe incluir: id_alumna, nombre, apellidos, ciudad y teléfono.
Inserta por lo menos 10 datos en la tabla creada en el ejercicio anterior (pueden ser inventados).
Haz una consulta que devuelva todos los registros de la tabla "alumnas" y conviértelo en Dataframe (no te olvides del nombre de las columnas).
Muestra los 3 primeros y tres últimos registros del Dataframe.
BONUS:
Haz una consulta para extraer las diferentes ciudades en las que hay alumnas.
Crea al menos dos Dataframes con la información de las alumnas de dos ciudades diferentes (usando dos queries).

In [1]:
#Librerías
import mysql.connector
from mysql.connector import errorcode
from sqlalchemy import create_engine,FLOAT, VARCHAR, INTEGER, DATE, SmallInteger
from sqlalchemy.sql.sqltypes import String
import pandas as pd

#### Prueba de conexión

In [ ]:
try:
    cnx = mysql.connector.connect(user= 'root', password='my-secret-pw', host='127.0.0.1')
    print("Conexión establecida con éxito")
except mysql.connector.Error as err:
    print(f"Error al conectar con MySQL: {err}")

#### Creación de Base de Datos

In [7]:
try:
    cnx = mysql.connector.connect(user= 'root', password='my-secret-pw', host='127.0.0.1')
    mycursor = cnx.cursor()
    mycursor.execute('CREATE DATABASE IF NOT EXISTS alumnas_promo_69')
    print("Se creó la base de datos.")
except:
    print("La base de datos ya existe.")

Se creó la base de datos.

#### Creación de la tabla.

In [ ]:
mycursor.execute("USE alumnas_promo_69")

query = "CREATE TABLE IF NOT EXISTS alumnas (id_alumna INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(100), apellidos VARCHAR(100), ciudad VARCHAR(100),telefono VARCHAR(15))"

mycursor.execute(query)

#### Inserción de datos.

In [ ]:
mycursor.execute("USE alumnas_promo_69")
query_datos_1= "INSERT INTO alumnas (nombre,apellidos,ciudad,telefono) VALUES (%s,%s,%s,%s)"
values_1=[('Ana Maria', 'Gonzalez', 'Madrid', '645821742'),
    ('Valeria', 'Montolla Perez', 'Madrid', '645333744'),
    ('Juana', 'Gomez Quintela', 'Barcelona', '624785799'),
    ('Celeste', 'Mendez Menendez', 'Lugo', '6726661948'),
    ('Natalia', 'Vallesteros', 'A Coruña', '6927855703'),
    ('Denise', 'Ruiz', 'Valencia', '6778215553'),    
    ('María', 'Pérez', 'Barcelona', '600333444'),
    ('Laura', 'López', 'Valencia', '600555666'),
    ('Clara', 'Martínez', 'Madrid', '600777888'),
    ('Sofía', 'Rodríguez', 'Sevilla', '600999000'),
    ('Eva', 'Fernández', 'Barcelona', '601234567'),
    ('Carmen', 'García', 'Valencia', '601345678'),
    ('Bea', 'Sánchez', 'Madrid', '601456789'),
    ('Isabel', 'Romero', 'Sevilla', '601567890'),
    ('Julia', 'Vázquez', 'Valencia', '601678901')]
mycursor.executemany(query_datos_1,values_1)
cnx.commit()
cnx.close()

#### Consulta de tabla y conversión con Pandas.

In [ ]:

try:
# Establecer conexción con MySQL.
    cnx= mysql.connector.connect(user='root', password='my-secret-pw', host='127.0.0.1')
    print("Conexión establecida con éxito")
except mysql.connector.Error as err:
    print(f"Error al conectar con MySQL: {err}")
# Posicionarse en la Base de Datos.
try:
    mycursor=cnx.cursor()
    mycursor.execute('USE alumnas_promo_69')
    print("Ya estamos en la BD 'alumnas_promo_69'.")
except mysql.connector.Error as err:
    print(f"No se pudo acceder a la Base de Datos: {err}")
# Realizar consulta de la tabla.
try:
    query_datos_2= ('SELECT * FROM alumnas')
    mycursor.execute(query_datos_2)
    resultado=mycursor.fetchall()
    print ("Se realizó la consulta a la tabla 'alumnas' y se almacenó en 'resultado'.")
except mysql.connector.Error as err:
    print(f"Error al acceder a la tabla: {err}")

Conexión establecida con éxito
Ya estamos en la BD 'alumnas_promo_69'.
Se realizó la consulta a la tabla 'alumnas' y se almacenó en 'resultado'.

In [21]:
df=pd.DataFrame(resultado, columns= ['legajo','nombre','apellidos','ciudad','telefono'])
df

    legajo     nombre        apellidos     ciudad    telefono
0        1  Ana Maria         Gonzalez     Madrid   645821742
1        2    Valeria   Montolla Perez     Madrid   645333744
2        3      Juana   Gomez Quintela  Barcelona   624785799
3        4    Celeste  Mendez Menendez       Lugo  6726661948
4        5    Natalia      Vallesteros   A Coruña  6927855703
5        6     Denise             Ruiz   Valencia  6778215553
6        7      María            Pérez  Barcelona   600333444
7        8      Laura            López   Valencia   600555666
8        9      Clara         Martínez     Madrid   600777888
9       10      Sofía        Rodríguez    Sevilla   600999000
10      11        Eva        Fernández  Barcelona   601234567
11      12     Carmen           García   Valencia   601345678
12      13        Bea          Sánchez     Madrid   601456789
13      14     Isabel           Romero    Sevilla   601567890
14      15      Julia          Vázquez   Valencia   601678901

In [ ]:
df.head(3)

   legajo     nombre       apellidos     ciudad   telefono
0       1  Ana Maria        Gonzalez     Madrid  645821742
1       2    Valeria  Montolla Perez     Madrid  645333744
2       3      Juana  Gomez Quintela  Barcelona  624785799

In [25]:
df.tail(3)

    legajo  nombre apellidos    ciudad   telefono
12      13     Bea   Sánchez    Madrid  601456789
13      14  Isabel    Romero   Sevilla  601567890
14      15   Julia   Vázquez  Valencia  601678901

In [27]:
try:
    mycursor.execute('SELECT DISTINCT ciudad FROM alumnas')
    ciudades=mycursor.fetchall()
    print("Las ciudades donde residen las alumnas se almacenaron en 'ciudades'.")
    print(ciudades)
except mysql.connector.Error as err:
    print(f"Se produjo un error: {err}")

Las ciudades donde residen las alumnas se almacenaron en 'ciudades'.
[('Madrid',), ('Barcelona',), ('Lugo',), ('A Coruña',), ('Valencia',), ('Sevilla',)]

#### BONUS

In [30]:
#Consultar tabla de alumnas con nombre que contengan letra e y no sean de Madrid.
try:
    query_datos_3= "SELECT * FROM alumnas WHERE nombre LIKE '%e%' AND ciudad <> 'Madrid'"
    mycursor.execute(query_datos_3)
    resultado_3=mycursor.fetchall()
except mysql.connector.Error as err:
    print(f"Se produjo un error: {err}")
#Consultar id_alumnas y apellido de alumnas de la ciudad de Valencia.
try:
    query_datos_4= "SELECT id_alumna,apellidos FROM alumnas WHERE ciudad = 'Valencia'"
    mycursor.execute(query_datos_4)
    resultado_4=mycursor.fetchall()
except mysql.connector.Error as err:
    print(f"Se produjo un error: {err}")

In [32]:
df_rdo_3=pd.DataFrame(resultado_3, columns=['legajo','nombre','apellidos','ciudad','telefono'])
df_rdo_3

   legajo   nombre        apellidos     ciudad    telefono
0       4  Celeste  Mendez Menendez       Lugo  6726661948
1       6   Denise             Ruiz   Valencia  6778215553
2      11      Eva        Fernández  Barcelona   601234567
3      12   Carmen           García   Valencia   601345678
4      14   Isabel           Romero    Sevilla   601567890

In [33]:
df_rdo_4=pd.DataFrame(resultado_4, columns= ['legajo','apellidos'])
df_rdo_4

   legajo apellidos
0       6      Ruiz
1       8     López
2      12    García
3      15   Vázquez

In [34]:
cnx.close()
print("Se cerró la conexión con Mysql.")

Se cerró la conexión con Mysql.