# BONUS

In [29]:
#Librerías
import pandas as pd
import mysql.connector
from mysql.connector import errorcode
import csv

In [30]:
# Establecer conexión con MySQL
try:
    cnx=mysql.connector.connect(user='root', password='my-secret-pw', host ='127.0.0.1', database= 'videoclub')
    print("Se estableció la conexión con Mysql.")
except mysql.connector.Error as err:
    print(f"No se pudo establecer la conexión. Error: {err}")

Se estableció la conexión con Mysql.

In [31]:
# Lectura de archivo .csv y generación de lista de values.

with open('tabla_clientes.csv', 'r') as f:
    datos = list(csv.reader(f))

In [32]:
print(datos)

[['Miguel', 'Navarro', 'Calle Central 449', '555-7961', 'ana@example.com', '2023-02-27'], ['Carmen', 'Navarro', 'Calle Norte 659', '555-8199', 'ana@example.com', '2024-10-25'], ['Sofía', 'Ruiz', 'Calle Oeste 504', '555-9360', 'ana@example.com', '2023-01-10'], ['Carlos', 'Herrera', 'Calle Sol 533', '555-7115', 'jorge@example.com', '2024-03-13'], ['Fernando', 'Navarro', 'Calle Estrella 446', '555-4390', 'ana@example.com', '2023-04-15'], ['Sofía', 'Pérez', 'Calle Central 606', '555-3117', 'claudia@example.com', '2023-03-01'], ['Marta', 'Domínguez', 'Calle Libertad 363', '555-9877', 'elena@example.com', '2024-08-27'], ['Claudia', 'Vega', 'Calle Central 146', '555-4130', 'luis@example.com', '2024-10-11'], ['Patricia', 'Castro', 'Calle Luna 821', '555-7720', 'maria@example.com', '2024-09-02'], ['Pedro', 'Gómez', 'Calle Central 831', '555-9197', 'sofia@example.com', '2023-07-12'], ['Alberto', 'Jiménez', 'Calle Sol 314', '555-1027', 'pedro@example.com', '2023-01-15'], ['Alberto', 'Herrera', 'Calle Unión 671', '555-1854', 'claudia@example.com', '2024-02-19'], ['Sofía', 'Ruiz', 'Calle Sol 859', '555-2454', 'sofia@example.com', '2023-04-20'], ['Andrés', 'Martínez', 'Calle Norte 325', '555-7860', 'ana@example.com', '2023-05-05'], ['Claudia', 'Vega', 'Calle Libertad 216', '555-5894', 'sofia@example.com', '2023-04-02'], ['Carlos', 'Ruiz', 'Calle Sol 886', '555-5109', 'sofia@example.com', '2023-05-13'], ['Rafael', 'Navarro', 'Calle Unión 873', '555-7701', 'sofia@example.com', '2024-07-22'], ['Luis', 'Fernández', 'Calle Sol 670', '555-2781', 'pedro@example.com', '2023-06-08'], ['Pedro', 'Castro', 'Calle Oeste 694', '555-8877', 'ana@example.com', '2024-07-23'], ['María', 'Navarro', 'Calle Central 667', '555-4713', 'elena@example.com', '2023-04-16'], ['Jorge', 'Ramírez', 'Calle Central 415', '555-3248', 'sofia@example.com', '2023-06-23'], ['Ana', 'Castro', 'Calle Central 697', '555-1925', 'fernando@example.com', '2024-04-04'], ['Alberto', 'Navarro', 'Calle Sur 593', '555-9001', 'ricardo@example.com', '2023-07-01'], ['Alberto', 'Gil', 'Calle Central 253', '555-5432', 'jorge@example.com', '2024-04-10'], ['Carmen', 'Torres', 'Calle Estrella 917', '555-2303', 'ana@example.com', '2023-10-08'], ['Jorge', 'Herrera', 'Calle Unión 434', '555-1761', 'pedro@example.com', '2023-06-11'], ['Andrés', 'Navarro', 'Calle Luna 464', '555-7657', 'sofia@example.com', '2024-01-09'], ['Elena', 'Ruiz', 'Calle Central 717', '555-2247', 'fernando@example.com', '2024-01-02'], ['Andrés', 'Ruiz', 'Calle Norte 573', '555-5793', 'pedro@example.com', '2024-07-23'], ['Ricardo', 'Sánchez', 'Calle Estrella 788', '555-4533', 'sofia@example.com', '2024-05-07'], ['Elena', 'López', 'Calle Estrella 824', '555-1749', 'luis@example.com', '2023-08-22'], ['Ricardo', 'Vega', 'Calle Sur 494', '555-9858', 'claudia@example.com', '2023-10-22'], ['Marta', 'Jiménez', 'Calle Central 925', '555-7477', 'elena@example.com', '2024-01-02'], ['Miguel', 'Jiménez', 'Calle Central 659', '555-8718', 'maria@example.com', '2023-03-19'], ['Pedro', 'Gómez', 'Calle Sur 386', '555-4699', 'luis@example.com', '2023-08-15'], ['Fernando', 'Domínguez', 'Calle Luna 225', '555-6503', 'fernando@example.com', '2023-04-16'], ['Lucía', 'Gómez', 'Calle Libertad 378', '555-1513', 'elena@example.com', '2023-12-10'], ['Carmen', 'Castro', 'Calle Luna 232', '555-8751', 'ricardo@example.com', '2023-10-07'], ['Miguel', 'Morales', 'Calle Luna 305', '555-8601', 'jorge@example.com', '2024-12-07'], ['Ana', 'Fernández', 'Calle Estrella 382', '555-9985', 'ricardo@example.com', '2023-12-08'], ['Ricardo', 'Vega', 'Calle Oeste 734', '555-5995', 'luis@example.com', '2024-07-24'], ['María', 'Gómez', 'Calle Estrella 237', '555-6815', 'pedro@example.com', '2023-08-19'], ['Laura', 'Domínguez', 'Calle Unión 151', '555-4818', 'elena@example.com', '2024-12-06'], ['Lucía', 'Pérez', 'Calle Sol 910', '555-2143', 'elena@example.com', '2024-10-15'], ['Pedro', 'Díaz', 'Calle Sol 915', '555-2977', 'sofia@example.com', '2023-06-06'], ['Laura', 'Domínguez', 'Calle Sur 709', '555-7469', 'luis@example.com', '2023-05-10'], ['Fernando', 'Domínguez', 'Calle Libertad 186', '555-7967', 'elena@example.com', '2024-03-24'], ['Marta', 'Herrera', 'Calle Este 337', '555-7922', 'maria@example.com', '2023-06-23'], ['Marta', 'Herrera', 'Calle Este 861', '555-8552', 'luis@example.com', '2024-10-22'], ['Rafael', 'Torres', 'Calle Este 789', '555-5440', 'luis@example.com', '2023-07-02'], ['Pedro', 'Martínez', 'Calle Sol 764', '555-7215', 'luis@example.com', '2024-12-28'], ['Marta', 'Torres', 'Calle Libertad 658', '555-3490', 'ana@example.com', '2023-12-01'], ['Ana', 'Vega', 'Calle Norte 408', '555-4785', 'ricardo@example.com', '2023-12-01'], ['Alberto', 'Ortega', 'Calle Unión 411', '555-2717', 'maria@example.com', '2023-11-25'], ['Patricia', 'Ortega', 'Calle Oeste 504', '555-4407', 'maria@example.com', '2024-03-16'], ['Miguel', 'Gil', 'Calle Oeste 799', '555-2886', 'ricardo@example.com', '2024-01-22'], ['Pedro', 'Torres', 'Calle Estrella 617', '555-2703', 'ricardo@example.com', '2023-05-21'], ['Luis', 'Gil', 'Calle Estrella 915', '555-7483', 'claudia@example.com', '2024-08-24'], ['María', 'Ruiz', 'Calle Norte 913', '555-5982', 'pedro@example.com', '2023-10-10'], ['Claudia', 'García', 'Calle Unión 160', '555-9489', 'ricardo@example.com', '2023-07-09'], ['Carlos', 'Ramírez', 'Calle Este 763', '555-8144', 'luis@example.com', '2023-05-25'], ['Patricia', 'Ortega', 'Calle Central 683', '555-1518', 'claudia@example.com', '2023-02-28'], ['Marta', 'Vega', 'Calle Estrella 655', '555-3033', 'jorge@example.com', '2023-04-27'], ['Laura', 'López', 'Calle Unión 112', '555-6676', 'pedro@example.com', '2024-02-14'], ['Pedro', 'Morales', 'Calle Sol 293', '555-3304', 'maria@example.com', '2024-09-18'], ['Pedro', 'Ruiz', 'Calle Libertad 158', '555-4636', 'luis@example.com', '2024-04-09'], ['Laura', 'Herrera', 'Calle Sur 985', '555-6217', 'sofia@example.com', '2024-07-07'], ['Ana', 'Vega', 'Calle Sur 483', '555-8452', 'fernando@example.com', '2024-03-07'], ['Miguel', 'Ortega', 'Calle Central 935', '555-2034', 'maria@example.com', '2023-08-16'], ['Rafael', 'Ortega', 'Calle Norte 335', '555-9679', 'fernando@example.com', '2023-02-07'], ['Ana', 'Jiménez', 'Calle Este 721', '555-7907', 'maria@example.com', '2023-04-14'], ['Carmen', 'Vega', 'Calle Este 640', '555-8066', 'luis@example.com', '2024-07-12'], ['Ana', 'Ramírez', 'Calle Oeste 912', '555-2052', 'sofia@example.com', '2024-10-25'], ['Miguel', 'Ruiz', 'Calle Central 547', '555-4678', 'jorge@example.com', '2023-01-28'], ['María', 'Pérez', 'Calle Estrella 944', '555-1545', 'ricardo@example.com', '2024-08-08'], ['Alberto', 'Martínez', 'Calle Sur 548', '555-3048', 'fernando@example.com', '2023-02-25'], ['Ana', 'Morales', 'Calle Luna 462', '555-7748', 'maria@example.com', '2024-03-06'], ['Luis', 'Domínguez', 'Calle Sur 383', '555-7868', 'fernando@example.com', '2024-05-08'], ['Laura', 'Fernández', 'Calle Este 743', '555-1873', 'elena@example.com', '2023-11-23'], ['Claudia', 'Sánchez', 'Calle Central 411', '555-9275', 'sofia@example.com', '2024-03-04'], ['Carmen', 'Torres', 'Calle Sur 770', '555-7737', 'claudia@example.com', '2023-09-21'], ['Carlos', 'Ramírez', 'Calle Sol 570', '555-4267', 'fernando@example.com', '2023-10-06'], ['Jorge', 'Vega', 'Calle Estrella 737', '555-3716', 'elena@example.com', '2023-08-21'], ['María', 'Domínguez', 'Calle Central 772', '555-8500', 'fernando@example.com', '2023-07-27'], ['Ricardo', 'Navarro', 'Calle Estrella 789', '555-1408', 'ana@example.com', '2024-10-09'], ['Rafael', 'Castro', 'Calle Central 655', '555-3156', 'maria@example.com', '2024-05-05'], ['Laura', 'Martínez', 'Calle Central 757', '555-6979', 'elena@example.com', '2024-06-06'], ['Ricardo', 'Martínez', 'Calle Sol 135', '555-1211', 'elena@example.com', '2024-05-05'], ['Carlos', 'Jiménez', 'Calle Luna 902', '555-6373', 'ricardo@example.com', '2024-02-11'], ['Elena', 'Morales', 'Calle Central 783', '555-4862', 'luis@example.com', '2023-03-08'], ['Carlos', 'Navarro', 'Calle Central 926', '555-5725', 'sofia@example.com', '2024-04-24'], ['Fernando', 'Pérez', 'Calle Central 930', '555-1933', 'maria@example.com', '2023-04-19'], ['Carmen', 'Herrera', 'Calle Sol 193', '555-3737', 'fernando@example.com', '2023-02-13'], ['Elena', 'Gómez', 'Calle Unión 888', '555-4388', 'maria@example.com', '2024-10-16'], ['Miguel', 'Torres', 'Calle Estrella 974', '555-6146', 'ana@example.com', '2024-11-14'], ['Ana', 'Ortega', 'Calle Central 942', '555-3603', 'luis@example.com', '2023-09-18'], ['Laura', 'Sánchez', 'Calle Estrella 775', '555-6308', 'maria@example.com', '2023-02-20'], ['Luis', 'Herrera', 'Calle Sol 924', '555-5736', 'fernando@example.com', '2024-04-13'], ['Sofía', 'García', 'Calle Estrella 679', '555-8406', 'sofia@example.com', '2023-01-18'], ['Luis', 'Fernández', 'Calle Sur 873', '555-3188', 'ricardo@example.com', '2023-08-06'], ['Marta', 'Ruiz', 'Calle Oeste 360', '555-8999', 'pedro@example.com', '2024-02-19'], ['Laura', 'Torres', 'Calle Sol 997', '555-8173', 'luis@example.com', '2023-04-27'], ['Lucía', 'Herrera', 'Calle Luna 278', '555-1620', 'ricardo@example.com', '2023-02-14'], ['Carmen', 'Martínez', 'Calle Central 578', '555-1861', 'ana@example.com', '2023-06-18'], ['Sofía', 'Jiménez', 'Calle Libertad 173', '555-8764', 'ana@example.com', '2023-03-20'], ['Lucía', 'Gil', 'Calle Sur 489', '555-4080', 'luis@example.com', '2024-06-03'], ['Ricardo', 'Ramírez', 'Calle Luna 883', '555-1927', 'elena@example.com', '2024-08-27'], ['Marta', 'Castro', 'Calle Sol 594', '555-1357', 'sofia@example.com', '2023-06-20'], ['Patricia', 'Ramírez', 'Calle Sol 611', '555-5645', 'sofia@example.com', '2023-02-04'], ['Fernando', 'Herrera', 'Calle Luna 716', '555-2393', 'elena@example.com', '2023-06-07'], ['Lucía', 'Vega', 'Calle Unión 839', '555-3057', 'luis@example.com', '2023-12-05'], ['Carmen', 'Herrera', 'Calle Central 976', '555-5503', 'ricardo@example.com', '2024-09-15'], ['Elena', 'Vega', 'Calle Central 609', '555-8470', 'elena@example.com', '2023-06-11'], ['Ana', 'Ortega', 'Calle Libertad 315', '555-7806', 'pedro@example.com', '2023-01-07'], ['Fernando', 'Díaz', 'Calle Unión 873', '555-2212', 'sofia@example.com', '2024-02-23'], ['Marta', 'García', 'Calle Central 989', '555-1272', 'ricardo@example.com', '2024-05-23'], ['Luis', 'Navarro', 'Calle Unión 452', '555-5123', 'luis@example.com', '2023-01-03'], ['Ricardo', 'Gómez', 'Calle Sur 653', '555-4393', 'jorge@example.com', '2024-10-20'], ['Lucía', 'Morales', 'Calle Libertad 323', '555-4056', 'fernando@example.com', '2024-03-06'], ['Alberto', 'Martínez', 'Calle Luna 943', '555-2072', 'ana@example.com', '2024-08-15'], ['Sofía', 'Vega', 'Calle Central 579', '555-2194', 'elena@example.com', '2024-10-16'], ['Andrés', 'Domínguez', 'Calle Luna 856', '555-7721', 'maria@example.com', '2023-07-21'], ['Sofía', 'Castro', 'Calle Estrella 314', '555-3622', 'claudia@example.com', '2024-07-15'], ['Rafael', 'Domínguez', 'Calle Oeste 249', '555-1325', 'ricardo@example.com', '2024-08-20'], ['Ricardo', 'Gil', 'Calle Central 865', '555-8520', 'maria@example.com', '2023-03-21'], ['Andrés', 'Castro', 'Calle Luna 268', '555-6848', 'ana@example.com', '2023-06-24'], ['María', 'García', 'Calle Luna 172', '555-9053', 'fernando@example.com', '2023-07-25'], ['Ana', 'Torres', 'Calle Luna 171', '555-3720', 'ricardo@example.com', '2023-08-26'], ['Jorge', 'López', 'Calle Estrella 881', '555-4385', 'jorge@example.com', '2024-07-24'], ['Elena', 'Morales', 'Calle Sol 374', '555-7380', 'jorge@example.com', '2023-06-24'], ['Elena', 'Pérez', 'Calle Sol 123', '555-5833', 'sofia@example.com', '2024-03-27'], ['Alberto', 'Herrera', 'Calle Oeste 396', '555-5794', 'elena@example.com', '2024-01-23'], ['Marta', 'Ruiz', 'Calle Oeste 976', '555-8968', 'ana@example.com', '2024-02-26'], ['Rafael', 'Torres', 'Calle Sol 359', '555-3197', 'luis@example.com', '2024-12-02'], ['Sofía', 'Ortega', 'Calle Sur 951', '555-9892', 'jorge@example.com', '2023-03-14'], ['Andrés', 'Díaz', 'Calle Unión 386', '555-1111', 'pedro@example.com', '2023-08-20'], ['Alberto', 'Domínguez', 'Calle Oeste 165', '555-1826', 'jorge@example.com', '2023-08-10'], ['Claudia', 'Torres', 'Calle Norte 223', '555-6169', 'pedro@example.com', '2024-11-21'], ['Lucía', 'Torres', 'Calle Luna 523', '555-6285', 'ana@example.com', '2023-09-22'], ['Andrés', 'Gil', 'Calle Sol 693', '555-9920', 'maria@example.com', '2023-02-12'], ['Alberto', 'Domínguez', 'Calle Este 693', '555-9713', 'ana@example.com', '2024-01-06'], ['Carmen', 'Díaz', 'Calle Este 920', '555-8421', 'luis@example.com', '2024-06-07'], ['Luis', 'Torres', 'Calle Norte 193', '555-4992', 'fernando@example.com', '2024-05-07'], ['Andrés', 'Ramírez', 'Calle Luna 849', '555-4985', 'luis@example.com', '2023-06-02'], ['Patricia', 'Pérez', 'Calle Sur 420', '555-8879', 'ricardo@example.com', '2024-02-25'], ['Alberto', 'Vega', 'Calle Luna 947', '555-8111', 'sofia@example.com', '2023-09-05'], ['Carlos', 'Fernández', 'Calle Sur 224', '555-4859', 'pedro@example.com', '2023-02-16'], ['Claudia', 'García', 'Calle Oeste 690', '555-9656', 'sofia@example.com', '2024-11-14'], ['Andrés', 'Domínguez', 'Calle Este 479', '555-8572', 'elena@example.com', '2023-09-06'], ['Sofía', 'Gil', 'Calle Libertad 402', '555-9261', 'maria@example.com', '2023-04-27']]

In [33]:
# Creación de cursor e ingreso de  datos en tabla 'clientes'.
try:
    mycursor=cnx.cursor()
    query_videoclub='USE videoclub'
    mycursor.execute(query_videoclub)
    print("Se accedió a la Base de Datos 'videoclub'.")
    mycursor.executemany(f"INSERT INTO clientes(nombre,apellido,direccion,telefono,email,fecha_registro) VALUES ({','.join(['%s']*len(datos[0]))})", datos)
    cnx.commit()
        
except mysql.connector.Error as err:
    print(f"No se pudo acceder a la tabla. Error: {err}")

Se accedió a la Base de Datos 'videoclub'.

In [34]:
# Se crea consulta a la tabla 'clientes' y se desconecta de mysql.
query_consulta_clientes='SELECT * FROM clientes'
mycursor.execute(query_consulta_clientes)
resultado=mycursor.fetchall()
print(resultado)
cnx.close()

[(1, 'Carlos', 'García', 'Av.Principal 123', '555-1234', 'carlos_garcia@example.com', datetime.date(2023, 1, 15)), (3, 'Miguel', 'López', 'Av. Tercera 789', '555-9876', 'miguel@example,com', datetime.date(2023, 3, 10)), (4, 'Miguel', 'Navarro', 'Calle Central 449', '555-7961', 'ana@example.com', datetime.date(2023, 2, 27)), (5, 'Carmen', 'Navarro', 'Calle Norte 659', '555-8199', 'ana@example.com', datetime.date(2024, 10, 25)), (6, 'Sofía', 'Ruiz', 'Calle Oeste 504', '555-9360', 'ana@example.com', datetime.date(2023, 1, 10)), (7, 'Carlos', 'Herrera', 'Calle Sol 533', '555-7115', 'jorge@example.com', datetime.date(2024, 3, 13)), (8, 'Fernando', 'Navarro', 'Calle Estrella 446', '555-4390', 'ana@example.com', datetime.date(2023, 4, 15)), (9, 'Sofía', 'Pérez', 'Calle Central 606', '555-3117', 'claudia@example.com', datetime.date(2023, 3, 1)), (10, 'Marta', 'Domínguez', 'Calle Libertad 363', '555-9877', 'elena@example.com', datetime.date(2024, 8, 27)), (11, 'Claudia', 'Vega', 'Calle Central 146', '555-4130', 'luis@example.com', datetime.date(2024, 10, 11)), (12, 'Patricia', 'Castro', 'Calle Luna 821', '555-7720', 'maria@example.com', datetime.date(2024, 9, 2)), (13, 'Pedro', 'Gómez', 'Calle Central 831', '555-9197', 'sofia@example.com', datetime.date(2023, 7, 12)), (14, 'Alberto', 'Jiménez', 'Calle Sol 314', '555-1027', 'pedro@example.com', datetime.date(2023, 1, 15)), (15, 'Alberto', 'Herrera', 'Calle Unión 671', '555-1854', 'claudia@example.com', datetime.date(2024, 2, 19)), (16, 'Sofía', 'Ruiz', 'Calle Sol 859', '555-2454', 'sofia@example.com', datetime.date(2023, 4, 20)), (17, 'Andrés', 'Martínez', 'Calle Norte 325', '555-7860', 'ana@example.com', datetime.date(2023, 5, 5)), (18, 'Claudia', 'Vega', 'Calle Libertad 216', '555-5894', 'sofia@example.com', datetime.date(2023, 4, 2)), (19, 'Carlos', 'Ruiz', 'Calle Sol 886', '555-5109', 'sofia@example.com', datetime.date(2023, 5, 13)), (20, 'Rafael', 'Navarro', 'Calle Unión 873', '555-7701', 'sofia@example.com', datetime.date(2024, 7, 22)), (21, 'Luis', 'Fernández', 'Calle Sol 670', '555-2781', 'pedro@example.com', datetime.date(2023, 6, 8)), (22, 'Pedro', 'Castro', 'Calle Oeste 694', '555-8877', 'ana@example.com', datetime.date(2024, 7, 23)), (23, 'María', 'Navarro', 'Calle Central 667', '555-4713', 'elena@example.com', datetime.date(2023, 4, 16)), (24, 'Jorge', 'Ramírez', 'Calle Central 415', '555-3248', 'sofia@example.com', datetime.date(2023, 6, 23)), (25, 'Ana', 'Castro', 'Calle Central 697', '555-1925', 'fernando@example.com', datetime.date(2024, 4, 4)), (26, 'Alberto', 'Navarro', 'Calle Sur 593', '555-9001', 'ricardo@example.com', datetime.date(2023, 7, 1)), (27, 'Alberto', 'Gil', 'Calle Central 253', '555-5432', 'jorge@example.com', datetime.date(2024, 4, 10)), (28, 'Carmen', 'Torres', 'Calle Estrella 917', '555-2303', 'ana@example.com', datetime.date(2023, 10, 8)), (29, 'Jorge', 'Herrera', 'Calle Unión 434', '555-1761', 'pedro@example.com', datetime.date(2023, 6, 11)), (30, 'Andrés', 'Navarro', 'Calle Luna 464', '555-7657', 'sofia@example.com', datetime.date(2024, 1, 9)), (31, 'Elena', 'Ruiz', 'Calle Central 717', '555-2247', 'fernando@example.com', datetime.date(2024, 1, 2)), (32, 'Andrés', 'Ruiz', 'Calle Norte 573', '555-5793', 'pedro@example.com', datetime.date(2024, 7, 23)), (33, 'Ricardo', 'Sánchez', 'Calle Estrella 788', '555-4533', 'sofia@example.com', datetime.date(2024, 5, 7)), (34, 'Elena', 'López', 'Calle Estrella 824', '555-1749', 'luis@example.com', datetime.date(2023, 8, 22)), (35, 'Ricardo', 'Vega', 'Calle Sur 494', '555-9858', 'claudia@example.com', datetime.date(2023, 10, 22)), (36, 'Marta', 'Jiménez', 'Calle Central 925', '555-7477', 'elena@example.com', datetime.date(2024, 1, 2)), (37, 'Miguel', 'Jiménez', 'Calle Central 659', '555-8718', 'maria@example.com', datetime.date(2023, 3, 19)), (38, 'Pedro', 'Gómez', 'Calle Sur 386', '555-4699', 'luis@example.com', datetime.date(2023, 8, 15)), (39, 'Fernando', 'Domínguez', 'Calle Luna 225', '555-6503', 'fernando@example.com', datetime.date(2023, 4, 16)), (40, 'Lucía', 'Gómez', 'Calle Libertad 378', '555-1513', 'elena@example.com', datetime.date(2023, 12, 10)), (41, 'Carmen', 'Castro', 'Calle Luna 232', '555-8751', 'ricardo@example.com', datetime.date(2023, 10, 7)), (42, 'Miguel', 'Morales', 'Calle Luna 305', '555-8601', 'jorge@example.com', datetime.date(2024, 12, 7)), (43, 'Ana', 'Fernández', 'Calle Estrella 382', '555-9985', 'ricardo@example.com', datetime.date(2023, 12, 8)), (44, 'Ricardo', 'Vega', 'Calle Oeste 734', '555-5995', 'luis@example.com', datetime.date(2024, 7, 24)), (45, 'María', 'Gómez', 'Calle Estrella 237', '555-6815', 'pedro@example.com', datetime.date(2023, 8, 19)), (46, 'Laura', 'Domínguez', 'Calle Unión 151', '555-4818', 'elena@example.com', datetime.date(2024, 12, 6)), (47, 'Lucía', 'Pérez', 'Calle Sol 910', '555-2143', 'elena@example.com', datetime.date(2024, 10, 15)), (48, 'Pedro', 'Díaz', 'Calle Sol 915', '555-2977', 'sofia@example.com', datetime.date(2023, 6, 6)), (49, 'Laura', 'Domínguez', 'Calle Sur 709', '555-7469', 'luis@example.com', datetime.date(2023, 5, 10)), (50, 'Fernando', 'Domínguez', 'Calle Libertad 186', '555-7967', 'elena@example.com', datetime.date(2024, 3, 24)), (51, 'Marta', 'Herrera', 'Calle Este 337', '555-7922', 'maria@example.com', datetime.date(2023, 6, 23)), (52, 'Marta', 'Herrera', 'Calle Este 861', '555-8552', 'luis@example.com', datetime.date(2024, 10, 22)), (53, 'Rafael', 'Torres', 'Calle Este 789', '555-5440', 'luis@example.com', datetime.date(2023, 7, 2)), (54, 'Pedro', 'Martínez', 'Calle Sol 764', '555-7215', 'luis@example.com', datetime.date(2024, 12, 28)), (55, 'Marta', 'Torres', 'Calle Libertad 658', '555-3490', 'ana@example.com', datetime.date(2023, 12, 1)), (56, 'Ana', 'Vega', 'Calle Norte 408', '555-4785', 'ricardo@example.com', datetime.date(2023, 12, 1)), (57, 'Alberto', 'Ortega', 'Calle Unión 411', '555-2717', 'maria@example.com', datetime.date(2023, 11, 25)), (58, 'Patricia', 'Ortega', 'Calle Oeste 504', '555-4407', 'maria@example.com', datetime.date(2024, 3, 16)), (59, 'Miguel', 'Gil', 'Calle Oeste 799', '555-2886', 'ricardo@example.com', datetime.date(2024, 1, 22)), (60, 'Pedro', 'Torres', 'Calle Estrella 617', '555-2703', 'ricardo@example.com', datetime.date(2023, 5, 21)), (61, 'Luis', 'Gil', 'Calle Estrella 915', '555-7483', 'claudia@example.com', datetime.date(2024, 8, 24)), (62, 'María', 'Ruiz', 'Calle Norte 913', '555-5982', 'pedro@example.com', datetime.date(2023, 10, 10)), (63, 'Claudia', 'García', 'Calle Unión 160', '555-9489', 'ricardo@example.com', datetime.date(2023, 7, 9)), (64, 'Carlos', 'Ramírez', 'Calle Este 763', '555-8144', 'luis@example.com', datetime.date(2023, 5, 25)), (65, 'Patricia', 'Ortega', 'Calle Central 683', '555-1518', 'claudia@example.com', datetime.date(2023, 2, 28)), (66, 'Marta', 'Vega', 'Calle Estrella 655', '555-3033', 'jorge@example.com', datetime.date(2023, 4, 27)), (67, 'Laura', 'López', 'Calle Unión 112', '555-6676', 'pedro@example.com', datetime.date(2024, 2, 14)), (68, 'Pedro', 'Morales', 'Calle Sol 293', '555-3304', 'maria@example.com', datetime.date(2024, 9, 18)), (69, 'Pedro', 'Ruiz', 'Calle Libertad 158', '555-4636', 'luis@example.com', datetime.date(2024, 4, 9)), (70, 'Laura', 'Herrera', 'Calle Sur 985', '555-6217', 'sofia@example.com', datetime.date(2024, 7, 7)), (71, 'Ana', 'Vega', 'Calle Sur 483', '555-8452', 'fernando@example.com', datetime.date(2024, 3, 7)), (72, 'Miguel', 'Ortega', 'Calle Central 935', '555-2034', 'maria@example.com', datetime.date(2023, 8, 16)), (73, 'Rafael', 'Ortega', 'Calle Norte 335', '555-9679', 'fernando@example.com', datetime.date(2023, 2, 7)), (74, 'Ana', 'Jiménez', 'Calle Este 721', '555-7907', 'maria@example.com', datetime.date(2023, 4, 14)), (75, 'Carmen', 'Vega', 'Calle Este 640', '555-8066', 'luis@example.com', datetime.date(2024, 7, 12)), (76, 'Ana', 'Ramírez', 'Calle Oeste 912', '555-2052', 'sofia@example.com', datetime.date(2024, 10, 25)), (77, 'Miguel', 'Ruiz', 'Calle Central 547', '555-4678', 'jorge@example.com', datetime.date(2023, 1, 28)), (78, 'María', 'Pérez', 'Calle Estrella 944', '555-1545', 'ricardo@example.com', datetime.date(2024, 8, 8)), (79, 'Alberto', 'Martínez', 'Calle Sur 548', '555-3048', 'fernando@example.com', datetime.date(2023, 2, 25)), (80, 'Ana', 'Morales', 'Calle Luna 462', '555-7748', 'maria@example.com', datetime.date(2024, 3, 6)), (81, 'Luis', 'Domínguez', 'Calle Sur 383', '555-7868', 'fernando@example.com', datetime.date(2024, 5, 8)), (82, 'Laura', 'Fernández', 'Calle Este 743', '555-1873', 'elena@example.com', datetime.date(2023, 11, 23)), (83, 'Claudia', 'Sánchez', 'Calle Central 411', '555-9275', 'sofia@example.com', datetime.date(2024, 3, 4)), (84, 'Carmen', 'Torres', 'Calle Sur 770', '555-7737', 'claudia@example.com', datetime.date(2023, 9, 21)), (85, 'Carlos', 'Ramírez', 'Calle Sol 570', '555-4267', 'fernando@example.com', datetime.date(2023, 10, 6)), (86, 'Jorge', 'Vega', 'Calle Estrella 737', '555-3716', 'elena@example.com', datetime.date(2023, 8, 21)), (87, 'María', 'Domínguez', 'Calle Central 772', '555-8500', 'fernando@example.com', datetime.date(2023, 7, 27)), (88, 'Ricardo', 'Navarro', 'Calle Estrella 789', '555-1408', 'ana@example.com', datetime.date(2024, 10, 9)), (89, 'Rafael', 'Castro', 'Calle Central 655', '555-3156', 'maria@example.com', datetime.date(2024, 5, 5)), (90, 'Laura', 'Martínez', 'Calle Central 757', '555-6979', 'elena@example.com', datetime.date(2024, 6, 6)), (91, 'Ricardo', 'Martínez', 'Calle Sol 135', '555-1211', 'elena@example.com', datetime.date(2024, 5, 5)), (92, 'Carlos', 'Jiménez', 'Calle Luna 902', '555-6373', 'ricardo@example.com', datetime.date(2024, 2, 11)), (93, 'Elena', 'Morales', 'Calle Central 783', '555-4862', 'luis@example.com', datetime.date(2023, 3, 8)), (94, 'Carlos', 'Navarro', 'Calle Central 926', '555-5725', 'sofia@example.com', datetime.date(2024, 4, 24)), (95, 'Fernando', 'Pérez', 'Calle Central 930', '555-1933', 'maria@example.com', datetime.date(2023, 4, 19)), (96, 'Carmen', 'Herrera', 'Calle Sol 193', '555-3737', 'fernando@example.com', datetime.date(2023, 2, 13)), (97, 'Elena', 'Gómez', 'Calle Unión 888', '555-4388', 'maria@example.com', datetime.date(2024, 10, 16)), (98, 'Miguel', 'Torres', 'Calle Estrella 974', '555-6146', 'ana@example.com', datetime.date(2024, 11, 14)), (99, 'Ana', 'Ortega', 'Calle Central 942', '555-3603', 'luis@example.com', datetime.date(2023, 9, 18)), (100, 'Laura', 'Sánchez', 'Calle Estrella 775', '555-6308', 'maria@example.com', datetime.date(2023, 2, 20)), (101, 'Luis', 'Herrera', 'Calle Sol 924', '555-5736', 'fernando@example.com', datetime.date(2024, 4, 13)), (102, 'Sofía', 'García', 'Calle Estrella 679', '555-8406', 'sofia@example.com', datetime.date(2023, 1, 18)), (103, 'Luis', 'Fernández', 'Calle Sur 873', '555-3188', 'ricardo@example.com', datetime.date(2023, 8, 6)), (104, 'Marta', 'Ruiz', 'Calle Oeste 360', '555-8999', 'pedro@example.com', datetime.date(2024, 2, 19)), (105, 'Laura', 'Torres', 'Calle Sol 997', '555-8173', 'luis@example.com', datetime.date(2023, 4, 27)), (106, 'Lucía', 'Herrera', 'Calle Luna 278', '555-1620', 'ricardo@example.com', datetime.date(2023, 2, 14)), (107, 'Carmen', 'Martínez', 'Calle Central 578', '555-1861', 'ana@example.com', datetime.date(2023, 6, 18)), (108, 'Sofía', 'Jiménez', 'Calle Libertad 173', '555-8764', 'ana@example.com', datetime.date(2023, 3, 20)), (109, 'Lucía', 'Gil', 'Calle Sur 489', '555-4080', 'luis@example.com', datetime.date(2024, 6, 3)), (110, 'Ricardo', 'Ramírez', 'Calle Luna 883', '555-1927', 'elena@example.com', datetime.date(2024, 8, 27)), (111, 'Marta', 'Castro', 'Calle Sol 594', '555-1357', 'sofia@example.com', datetime.date(2023, 6, 20)), (112, 'Patricia', 'Ramírez', 'Calle Sol 611', '555-5645', 'sofia@example.com', datetime.date(2023, 2, 4)), (113, 'Fernando', 'Herrera', 'Calle Luna 716', '555-2393', 'elena@example.com', datetime.date(2023, 6, 7)), (114, 'Lucía', 'Vega', 'Calle Unión 839', '555-3057', 'luis@example.com', datetime.date(2023, 12, 5)), (115, 'Carmen', 'Herrera', 'Calle Central 976', '555-5503', 'ricardo@example.com', datetime.date(2024, 9, 15)), (116, 'Elena', 'Vega', 'Calle Central 609', '555-8470', 'elena@example.com', datetime.date(2023, 6, 11)), (117, 'Ana', 'Ortega', 'Calle Libertad 315', '555-7806', 'pedro@example.com', datetime.date(2023, 1, 7)), (118, 'Fernando', 'Díaz', 'Calle Unión 873', '555-2212', 'sofia@example.com', datetime.date(2024, 2, 23)), (119, 'Marta', 'García', 'Calle Central 989', '555-1272', 'ricardo@example.com', datetime.date(2024, 5, 23)), (120, 'Luis', 'Navarro', 'Calle Unión 452', '555-5123', 'luis@example.com', datetime.date(2023, 1, 3)), (121, 'Ricardo', 'Gómez', 'Calle Sur 653', '555-4393', 'jorge@example.com', datetime.date(2024, 10, 20)), (122, 'Lucía', 'Morales', 'Calle Libertad 323', '555-4056', 'fernando@example.com', datetime.date(2024, 3, 6)), (123, 'Alberto', 'Martínez', 'Calle Luna 943', '555-2072', 'ana@example.com', datetime.date(2024, 8, 15)), (124, 'Sofía', 'Vega', 'Calle Central 579', '555-2194', 'elena@example.com', datetime.date(2024, 10, 16)), (125, 'Andrés', 'Domínguez', 'Calle Luna 856', '555-7721', 'maria@example.com', datetime.date(2023, 7, 21)), (126, 'Sofía', 'Castro', 'Calle Estrella 314', '555-3622', 'claudia@example.com', datetime.date(2024, 7, 15)), (127, 'Rafael', 'Domínguez', 'Calle Oeste 249', '555-1325', 'ricardo@example.com', datetime.date(2024, 8, 20)), (128, 'Ricardo', 'Gil', 'Calle Central 865', '555-8520', 'maria@example.com', datetime.date(2023, 3, 21)), (129, 'Andrés', 'Castro', 'Calle Luna 268', '555-6848', 'ana@example.com', datetime.date(2023, 6, 24)), (130, 'María', 'García', 'Calle Luna 172', '555-9053', 'fernando@example.com', datetime.date(2023, 7, 25)), (131, 'Ana', 'Torres', 'Calle Luna 171', '555-3720', 'ricardo@example.com', datetime.date(2023, 8, 26)), (132, 'Jorge', 'López', 'Calle Estrella 881', '555-4385', 'jorge@example.com', datetime.date(2024, 7, 24)), (133, 'Elena', 'Morales', 'Calle Sol 374', '555-7380', 'jorge@example.com', datetime.date(2023, 6, 24)), (134, 'Elena', 'Pérez', 'Calle Sol 123', '555-5833', 'sofia@example.com', datetime.date(2024, 3, 27)), (135, 'Alberto', 'Herrera', 'Calle Oeste 396', '555-5794', 'elena@example.com', datetime.date(2024, 1, 23)), (136, 'Marta', 'Ruiz', 'Calle Oeste 976', '555-8968', 'ana@example.com', datetime.date(2024, 2, 26)), (137, 'Rafael', 'Torres', 'Calle Sol 359', '555-3197', 'luis@example.com', datetime.date(2024, 12, 2)), (138, 'Sofía', 'Ortega', 'Calle Sur 951', '555-9892', 'jorge@example.com', datetime.date(2023, 3, 14)), (139, 'Andrés', 'Díaz', 'Calle Unión 386', '555-1111', 'pedro@example.com', datetime.date(2023, 8, 20)), (140, 'Alberto', 'Domínguez', 'Calle Oeste 165', '555-1826', 'jorge@example.com', datetime.date(2023, 8, 10)), (141, 'Claudia', 'Torres', 'Calle Norte 223', '555-6169', 'pedro@example.com', datetime.date(2024, 11, 21)), (142, 'Lucía', 'Torres', 'Calle Luna 523', '555-6285', 'ana@example.com', datetime.date(2023, 9, 22)), (143, 'Andrés', 'Gil', 'Calle Sol 693', '555-9920', 'maria@example.com', datetime.date(2023, 2, 12)), (144, 'Alberto', 'Domínguez', 'Calle Este 693', '555-9713', 'ana@example.com', datetime.date(2024, 1, 6)), (145, 'Carmen', 'Díaz', 'Calle Este 920', '555-8421', 'luis@example.com', datetime.date(2024, 6, 7)), (146, 'Luis', 'Torres', 'Calle Norte 193', '555-4992', 'fernando@example.com', datetime.date(2024, 5, 7)), (147, 'Andrés', 'Ramírez', 'Calle Luna 849', '555-4985', 'luis@example.com', datetime.date(2023, 6, 2)), (148, 'Patricia', 'Pérez', 'Calle Sur 420', '555-8879', 'ricardo@example.com', datetime.date(2024, 2, 25)), (149, 'Alberto', 'Vega', 'Calle Luna 947', '555-8111', 'sofia@example.com', datetime.date(2023, 9, 5)), (150, 'Carlos', 'Fernández', 'Calle Sur 224', '555-4859', 'pedro@example.com', datetime.date(2023, 2, 16)), (151, 'Claudia', 'García', 'Calle Oeste 690', '555-9656', 'sofia@example.com', datetime.date(2024, 11, 14)), (152, 'Andrés', 'Domínguez', 'Calle Este 479', '555-8572', 'elena@example.com', datetime.date(2023, 9, 6)), (153, 'Sofía', 'Gil', 'Calle Libertad 402', '555-9261', 'maria@example.com', datetime.date(2023, 4, 27))]

In [35]:
# Se crea un DataFrame de la ultima consulta: 'clientes'.
df=pd.DataFrame(resultado,columns=('id_cliente','nombre','apellido','direccion','teléfono','email','fecha_registro'))
df

,id_cliente,nombre,apellido,direccion,teléfono,email,fecha_registro
0,1,Carlos,García,Av.Principal 123,555-1234,carlos_garcia@example.com,2023-01-15
1,3,Miguel,López,Av. Tercera 789,555-9876,"miguel@example,com",2023-03-10
2,4,Miguel,Navarro,Calle Central 449,555-7961,ana@example.com,2023-02-27
3,5,Carmen,Navarro,Calle Norte 659,555-8199,ana@example.com,2024-10-25
4,6,Sofía,Ruiz,Calle Oeste 504,555-9360,ana@example.com,2023-01-10
...,...,...,...,...,...,...,...
147,149,Alberto,Vega,Calle Luna 947,555-8111,sofia@example.com,2023-09-05
148,150,Carlos,Fernández,Calle Sur 224,555-4859,pedro@example.com,2023-02-16
149,151,Claudia,García,Calle Oeste 690,555-9656,sofia@example.com,2024-11-14
150,152,Andrés,Domínguez,Calle Este 479,555-8572,elena@example.com,2023-09-06
151,153,Sofía,Gil,Calle Libertad 402,555-9261,maria@example.com,2023-04-27

In [36]:
df.head(5)

,id_cliente,nombre,apellido,direccion,teléfono,email,fecha_registro
0,1,Carlos,García,Av.Principal 123,555-1234,carlos_garcia@example.com,2023-01-15
1,3,Miguel,López,Av. Tercera 789,555-9876,"miguel@example,com",2023-03-10
2,4,Miguel,Navarro,Calle Central 449,555-7961,ana@example.com,2023-02-27
3,5,Carmen,Navarro,Calle Norte 659,555-8199,ana@example.com,2024-10-25
4,6,Sofía,Ruiz,Calle Oeste 504,555-9360,ana@example.com,2023-01-10

In [37]:
df.tail(5)

,id_cliente,nombre,apellido,direccion,teléfono,email,fecha_registro
147,149,Alberto,Vega,Calle Luna 947,555-8111,sofia@example.com,2023-09-05
148,150,Carlos,Fernández,Calle Sur 224,555-4859,pedro@example.com,2023-02-16
149,151,Claudia,García,Calle Oeste 690,555-9656,sofia@example.com,2024-11-14
150,152,Andrés,Domínguez,Calle Este 479,555-8572,elena@example.com,2023-09-06
151,153,Sofía,Gil,Calle Libertad 402,555-9261,maria@example.com,2023-04-27

In [38]:
df.sample(10)

,id_cliente,nombre,apellido,direccion,teléfono,email,fecha_registro
10,12,Patricia,Castro,Calle Luna 821,555-7720,maria@example.com,2024-09-02
147,149,Alberto,Vega,Calle Luna 947,555-8111,sofia@example.com,2023-09-05
112,114,Lucía,Vega,Calle Unión 839,555-3057,luis@example.com,2023-12-05
140,142,Lucía,Torres,Calle Luna 523,555-6285,ana@example.com,2023-09-22
54,56,Ana,Vega,Calle Norte 408,555-4785,ricardo@example.com,2023-12-01
16,18,Claudia,Vega,Calle Libertad 216,555-5894,sofia@example.com,2023-04-02
37,39,Fernando,Domínguez,Calle Luna 225,555-6503,fernando@example.com,2023-04-16
124,126,Sofía,Castro,Calle Estrella 314,555-3622,claudia@example.com,2024-07-15
13,15,Alberto,Herrera,Calle Unión 671,555-1854,claudia@example.com,2024-02-19
59,61,Luis,Gil,Calle Estrella 915,555-7483,claudia@example.com,2024-08-24